### ISSUE TITLE
Cordova Deep Link Support

### ISSUE THREAD

**Issue by Hirbod** [TuneOSS/phonegap-plugin#14]
Hi,

does this Cordova Plugin have support für DeepLinking/Universal Links on iOS and Android?
This is the most important feature for us with tracking.

From first look, I couldn't see any listeners from the JS-Side, only native tutorials. @john-gu

**Comment by Hirbod** [comment]
The only thing I've found is
https://github.com/TuneOSS/phonegap-plugin/blob/master/www/TunePlugin.js#L34

But I can't find any "registerDeeplinkListener" function. Could you please describe that a little more?

**Comment by john-gu** [comment]
Hi @Hirbod, that API call appears to have not gotten migrated over when the plugin was updated. I will create a ticket to do so.

**Comment by Hirbod** [comment]
Any ETA?

**Comment by john-gu** [comment]
We're currently in the middle of a plugin update so I will slot this into the upcoming release. We plan to release within the next week.

**Comment by john-gu** [comment]
Hi @Hirbod, the 7.0.0 release of the `cordova-plugin-tune` plugin now contains the `registerDeeplinkListener` API call.
